name: ciofs2
channel_priority: strict
channels:
  - conda-forge
  - pyviz
dependencies:
  # Required for full project functionality (don't remove)
  - pytest
  # Examples (remove and add as needed)
  - cartopy
  - cf_pandas
  - cmocean
  - dask
  - dataretrieval
  - datetimerange
  # - datashader  # need dev github version of holoviews to avoid nanosecond bug using datashader with ADCP plots: https://github.com/holoviz/holoviews/pull/5662
  # - geoviews
  - ghp-import
  - h5netcdf
  - holoviews
  - hvplot
  # - intake-axds  # going to install locally
  # - intake-erddap  # going to install locally
  - jupyter-book
  - netcdf4
  - numpy
  - matplotlib-base
  # - ocean-model-skill-assessor  # get from pypi until conda-forge is updated
  - pandas
  - pip
  - python-oceans
  - seaborn
  - xarray
  # - xcmocean
  - pip:
    - datashader
    - jupyter_bokeh
    - pillow==9.4.0  # Otherwise get error ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
    - ocean-model-skill-assessor
    - noaa_coops  # should be included with intake-coops in the future
    - git+https://github.com/axiom-data-science/intake-coops
    - git+https://github.com/intake/intake
    - git+https://github.com/moflaher/ttide_py.git@newversionstring
